# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_iserver_account_pnl_partitioned_get(self) -> None:
        """Test case for iserver_account_pnl_partitioned_get

        PnL for the selected account
        """
        pass

    def test_iserver_account_post(self) -> None:
        """Test case for iserver_account_post

        Switch Account
        """
        pass

    def test_iserver_accounts_get(self) -> None:
        """Test case for iserver_accounts_get

        Brokerage Accounts
        """
        pass

    def test_portfolio_account_id_ledger_get(self) -> None:
        """Test case for portfolio_account_id_ledger_get

        Account Ledger
        """
        pass

    def test_portfolio_account_id_meta_get(self) -> None:
        """Test case for portfolio_account_id_meta_get

        Account Information
        """
        pass

    def test_portfolio_account_id_summary_get(self) -> None:
        """Test case for portfolio_account_id_summary_get

        Account Summary
        """
        pass

    def test_portfolio_accounts_get(self) -> None:
        """Test case for portfolio_accounts_get

        Portfolio Accounts
        """
        pass

    def test_portfolio_subaccounts2_get(self) -> None:
        """Test case for portfolio_subaccounts2_get

        List of Sub-Accounts (Large Accounts)
        """
        pass

    def test_portfolio_subaccounts_get(self) -> None:
        """Test case for portfolio_subaccounts_get

        List of Sub-Accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
