# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.position_data import PositionData

class TestPositionData(unittest.TestCase):
    """PositionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionData:
        """Test PositionData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionData`
        """
        model = PositionData()
        if include_optional:
            return PositionData(
                conid = 1.337,
                position = 1.337,
                avg_cost = 1.337
            )
        else:
            return PositionData(
        )
        """

    def testPositionData(self):
        """Test PositionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
