# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trsrv_secdef_schedule_get200_response_schedules_inner_trading_times import TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes

class TestTrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes(unittest.TestCase):
    """TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes:
        """Test TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes`
        """
        model = TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes()
        if include_optional:
            return TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes(
                opening_time = 56,
                closing_time = 56,
                cancel_day_orders = ''
            )
        else:
            return TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes(
        )
        """

    def testTrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes(self):
        """Test TrsrvSecdefScheduleGet200ResponseSchedulesInnerTradingTimes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
