# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secdef_inner import SecdefInner

class TestSecdefInner(unittest.TestCase):
    """SecdefInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecdefInner:
        """Test SecdefInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecdefInner`
        """
        model = SecdefInner()
        if include_optional:
            return SecdefInner(
                conid = 56,
                currency = '',
                cross_currency = True,
                time = 56,
                chinese_name = '',
                all_exchanges = '',
                listing_exchange = '',
                name = '',
                asset_class = '',
                expiry = '',
                last_trading_day = '',
                group = '',
                put_or_call = '',
                sector = '',
                sector_group = '',
                strike = 1.337,
                ticker = '',
                und_conid = 56,
                multiplier = 56,
                type = '',
                und_comp = '',
                und_sym = '',
                has_options = True,
                full_name = '',
                is_us = True,
                increment_rules = openapi_client.models.secdef_inner_increment_rules.secdef_inner_incrementRules(
                    lower_edge = 1.337, 
                    increment = 1.337, )
            )
        else:
            return SecdefInner(
        )
        """

    def testSecdefInner(self):
        """Test SecdefInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
