# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fyi_settings_get200_response_inner import FyiSettingsGet200ResponseInner

class TestFyiSettingsGet200ResponseInner(unittest.TestCase):
    """FyiSettingsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FyiSettingsGet200ResponseInner:
        """Test FyiSettingsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FyiSettingsGet200ResponseInner`
        """
        model = FyiSettingsGet200ResponseInner()
        if include_optional:
            return FyiSettingsGet200ResponseInner(
                a = 56,
                fc = '',
                h = 56,
                fd = '',
                fn = ''
            )
        else:
            return FyiSettingsGet200ResponseInner(
        )
        """

    def testFyiSettingsGet200ResponseInner(self):
        """Test FyiSettingsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
