# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_account_post200_response import IserverAccountPost200Response

class TestIserverAccountPost200Response(unittest.TestCase):
    """IserverAccountPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverAccountPost200Response:
        """Test IserverAccountPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverAccountPost200Response`
        """
        model = IserverAccountPost200Response()
        if include_optional:
            return IserverAccountPost200Response(
                set = True,
                acct_id = ''
            )
        else:
            return IserverAccountPost200Response(
        )
        """

    def testIserverAccountPost200Response(self):
        """Test IserverAccountPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
