# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.modify_order import ModifyOrder

class TestModifyOrder(unittest.TestCase):
    """ModifyOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModifyOrder:
        """Test ModifyOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModifyOrder`
        """
        model = ModifyOrder()
        if include_optional:
            return ModifyOrder(
                acct_id = '',
                conid = 56,
                order_type = '',
                outside_rth = True,
                price = 1.337,
                aux_price = 1.337,
                side = '',
                listing_exchange = '',
                ticker = '',
                tif = 'tif = DAY to tif = GTC',
                quantity = 1.337,
                deactivated = True
            )
        else:
            return ModifyOrder(
        )
        """

    def testModifyOrder(self):
        """Test ModifyOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
