# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.alert_response import AlertResponse

class TestAlertResponse(unittest.TestCase):
    """AlertResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertResponse:
        """Test AlertResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertResponse`
        """
        model = AlertResponse()
        if include_optional:
            return AlertResponse(
                account = '',
                order_id = 56,
                alert_name = '',
                alert_message = '',
                alert_active = 56,
                alert_repeatable = 56,
                alert_email = '',
                alert_send_message = 56,
                tif = '',
                expire_time = '20201105-19:51:14',
                order_status = 'Submitted',
                outside_rth = 56,
                itws_orders_only = 56,
                alert_show_popup = 56,
                alert_triggered = True,
                order_not_editable = True,
                tool_id = 56,
                alert_play_audio = '',
                alert_mta_currency = '',
                alert_mta_defaults = '',
                time_zone = '',
                alert_default_type = '',
                condition_size = 56,
                condition_outside_rth = 56,
                conditions = [
                    openapi_client.models.alert_response_conditions_inner.alert_response_conditions_inner(
                        condition_type = 56, 
                        conidex = '8314@SMART', 
                        contract_description_1 = 'FB Stock (NASDAQ.NMS)', 
                        condition_operator = '- >= - <=
', 
                        condition_trigger_method = '0', 
                        condition_value = '220', 
                        condition_logic_bind = '', 
                        condition_time_zone = '', )
                    ]
            )
        else:
            return AlertResponse(
        )
        """

    def testAlertResponse(self):
        """Test AlertResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
