# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.allocation_inner_sector_short import AllocationInnerSectorShort

class TestAllocationInnerSectorShort(unittest.TestCase):
    """AllocationInnerSectorShort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllocationInnerSectorShort:
        """Test AllocationInnerSectorShort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllocationInnerSectorShort`
        """
        model = AllocationInnerSectorShort()
        if include_optional:
            return AllocationInnerSectorShort(
                industrial = 1.337,
                consumer = 1.337,
                diversified = 1.337
            )
        else:
            return AllocationInnerSectorShort(
        )
        """

    def testAllocationInnerSectorShort(self):
        """Test AllocationInnerSectorShort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
