# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_contract_rules_post200_response_rules_inner_can_trade_acct_ids_inner import IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner

class TestIserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner(unittest.TestCase):
    """IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner:
        """Test IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner`
        """
        model = IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner()
        if include_optional:
            return IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner(
                var_0 = ''
            )
        else:
            return IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner(
        )
        """

    def testIserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner(self):
        """Test IserverContractRulesPost200ResponseRulesInnerCanTradeAcctIdsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
