# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_contract_rules_post200_response_rules_inner_order_defaults_inner_string_inner import IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner

class TestIserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner(unittest.TestCase):
    """IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner:
        """Test IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner`
        """
        model = IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner()
        if include_optional:
            return IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner(
                orth = True,
                sp = '',
                lp = '',
                pc = '',
                ta = '',
                tu = '',
                roa = '',
                rop = '',
                tt = '',
                unp = True
            )
        else:
            return IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner(
        )
        """

    def testIserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner(self):
        """Test IserverContractRulesPost200ResponseRulesInnerOrderDefaultsInnerStringInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
