# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account_parent import AccountParent

class TestAccountParent(unittest.TestCase):
    """AccountParent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountParent:
        """Test AccountParent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountParent`
        """
        model = AccountParent()
        if include_optional:
            return AccountParent(
                mmc = [
                    ''
                    ],
                account_id = '',
                is_m_parent = True,
                is_m_child = True,
                is_multiplex = True
            )
        else:
            return AccountParent(
        )
        """

    def testAccountParent(self):
        """Test AccountParent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
