# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_contract_rules_post200_response_rules_inner import IserverContractRulesPost200ResponseRulesInner

class TestIserverContractRulesPost200ResponseRulesInner(unittest.TestCase):
    """IserverContractRulesPost200ResponseRulesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverContractRulesPost200ResponseRulesInner:
        """Test IserverContractRulesPost200ResponseRulesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverContractRulesPost200ResponseRulesInner`
        """
        model = IserverContractRulesPost200ResponseRulesInner()
        if include_optional:
            return IserverContractRulesPost200ResponseRulesInner(
                algo_eligible = True,
                can_trade_acct_ids = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_can_trade_acct_ids_inner._iserver_contract_rules_post_200_response_rules_inner_canTradeAcctIds_inner(
                        0 = '', )
                    ],
                error = '',
                order_types = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_order_types_inner._iserver_contract_rules_post_200_response_rules_inner_orderTypes_inner(
                        0 = '', )
                    ],
                ibalgo_types = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_ibalgo_types_inner._iserver_contract_rules_post_200_response_rules_inner_ibalgoTypes_inner(
                        0 = '', )
                    ],
                fraq_types = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_fraq_types_inner._iserver_contract_rules_post_200_response_rules_inner_fraqTypes_inner(
                        0 = '', )
                    ],
                cqt_types = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_cqt_types_inner._iserver_contract_rules_post_200_response_rules_inner_cqtTypes_inner(
                        0 = '', )
                    ],
                order_defaults = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_order_defaults_inner._iserver_contract_rules_post_200_response_rules_inner_orderDefaults_inner(
                        string = [
                            openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_order_defaults_inner_string_inner._iserver_contract_rules_post_200_response_rules_inner_orderDefaults_inner_string_inner(
                                orth = True, 
                                sp = '', 
                                lp = '', 
                                pc = '', 
                                ta = '', 
                                tu = '', 
                                roa = '', 
                                rop = '', 
                                tt = '', 
                                unp = True, )
                            ], )
                    ],
                order_types_outside = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_order_types_outside_inner._iserver_contract_rules_post_200_response_rules_inner_orderTypesOutside_inner(
                        0 = '', )
                    ],
                default_size = 56,
                cash_size = 56,
                size_increment = 56,
                tif_types = [
                    openapi_client.models._iserver_contract_rules_post_200_response_rules_inner_tif_types_inner._iserver_contract_rules_post_200_response_rules_inner_tifTypes_inner(
                        0 = '', )
                    ],
                default_tif = '',
                limit_price = 1.337,
                stopprice = 1.337,
                order_origination = 1.337,
                preview = True,
                display_size = 1.337,
                fraq_int = 1.337,
                cash_ccy = '',
                cash_qty_incr = 1.337,
                price_magnifier = 1.337,
                negative_capable = True,
                increment = 1.337,
                increment_digits = 56
            )
        else:
            return IserverContractRulesPost200ResponseRulesInner(
        )
        """

    def testIserverContractRulesPost200ResponseRulesInner(self):
        """Test IserverContractRulesPost200ResponseRulesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
