# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account import Account

class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Account:
        """Test Account
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Account`
        """
        model = Account()
        if include_optional:
            return Account(
                id = '',
                account_id = 'U12345678 for Individual Live Accounts, DU12345678 for Individual Paper Accounts',
                account_van = '',
                account_title = '',
                display_name = 'accountTitle',
                account_alias = '',
                account_status = 1.337,
                currency = 'AUD',
                type = 'INDIVIDUAL',
                trading_type = '',
                faclient = True,
                clearing_status = 'O',
                covestor = True,
                parent = openapi_client.models.account_parent.account_parent(
                    mmc = [
                        ''
                        ], 
                    account_id = '', 
                    is_m_parent = True, 
                    is_m_child = True, 
                    is_multiplex = True, ),
                desc = ''
            )
        else:
            return Account(
        )
        """

    def testAccount(self):
        """Test Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
