# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_account_account_id_alert_activate_post200_response import IserverAccountAccountIdAlertActivatePost200Response

class TestIserverAccountAccountIdAlertActivatePost200Response(unittest.TestCase):
    """IserverAccountAccountIdAlertActivatePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverAccountAccountIdAlertActivatePost200Response:
        """Test IserverAccountAccountIdAlertActivatePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverAccountAccountIdAlertActivatePost200Response`
        """
        model = IserverAccountAccountIdAlertActivatePost200Response()
        if include_optional:
            return IserverAccountAccountIdAlertActivatePost200Response(
                request_id = 56,
                order_id = 56,
                success = True,
                text = '',
                order_status = '',
                failure_list = ''
            )
        else:
            return IserverAccountAccountIdAlertActivatePost200Response(
        )
        """

    def testIserverAccountAccountIdAlertActivatePost200Response(self):
        """Test IserverAccountAccountIdAlertActivatePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
