# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_scanner_params_get200_response_instrument_list_inner import IserverScannerParamsGet200ResponseInstrumentListInner

class TestIserverScannerParamsGet200ResponseInstrumentListInner(unittest.TestCase):
    """IserverScannerParamsGet200ResponseInstrumentListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverScannerParamsGet200ResponseInstrumentListInner:
        """Test IserverScannerParamsGet200ResponseInstrumentListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverScannerParamsGet200ResponseInstrumentListInner`
        """
        model = IserverScannerParamsGet200ResponseInstrumentListInner()
        if include_optional:
            return IserverScannerParamsGet200ResponseInstrumentListInner(
                display_name = '',
                type = '',
                filters = [
                    ''
                    ]
            )
        else:
            return IserverScannerParamsGet200ResponseInstrumentListInner(
        )
        """

    def testIserverScannerParamsGet200ResponseInstrumentListInner(self):
        """Test IserverScannerParamsGet200ResponseInstrumentListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
