# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trade import Trade

class TestTrade(unittest.TestCase):
    """Trade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Trade:
        """Test Trade
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Trade`
        """
        model = Trade()
        if include_optional:
            return Trade(
                execution_id = '',
                symbol = '',
                side = 'B',
                order_description = '',
                trade_time = '',
                trade_time_r = 1.337,
                size = '',
                price = '',
                order_ref = '',
                submitter = '',
                exchange = '',
                commission = 1.337,
                net_amount = 1.337,
                account = '',
                acount_code = '',
                company_name = '',
                contract_description_1 = 'FB Stock (NASDAQ.NMS)',
                sec_type = 'STK, FUT, OPT',
                conid = '',
                conidex = '',
                position = '',
                clearing_id = '',
                clearing_name = '',
                liquidation_trade = 1.337
            )
        else:
            return Trade(
        )
        """

    def testTrade(self):
        """Test Trade"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
