# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.session_api import SessionApi


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionApi()

    def tearDown(self) -> None:
        pass

    def test_iserver_auth_status_post(self) -> None:
        """Test case for iserver_auth_status_post

        Authentication Status
        """
        pass

    def test_iserver_reauthenticate_post(self) -> None:
        """Test case for iserver_reauthenticate_post

        Tries to re-authenticate to Brokerage
        """
        pass

    def test_logout_post(self) -> None:
        """Test case for logout_post

        Ends the current session
        """
        pass

    def test_sso_validate_get(self) -> None:
        """Test case for sso_validate_get

        Validate SSO
        """
        pass

    def test_tickle_post(self) -> None:
        """Test case for tickle_post

        Ping the server to keep the session open
        """
        pass


if __name__ == '__main__':
    unittest.main()
