# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contract_rules import ContractRules

class TestContractRules(unittest.TestCase):
    """ContractRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractRules:
        """Test ContractRules
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractRules`
        """
        model = ContractRules()
        if include_optional:
            return ContractRules(
                order_types = [
                    ''
                    ],
                order_types_outside = [
                    ''
                    ],
                default_size = 1.337,
                size_increment = 1.337,
                tif_types = [
                    ''
                    ],
                limit_price = 1.337,
                stopprice = 1.337,
                preview = True,
                display_size = '',
                increment = ''
            )
        else:
            return ContractRules(
        )
        """

    def testContractRules(self):
        """Test ContractRules"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
