# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_status import AuthStatus

class TestAuthStatus(unittest.TestCase):
    """AuthStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthStatus:
        """Test AuthStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthStatus`
        """
        model = AuthStatus()
        if include_optional:
            return AuthStatus(
                authenticated = True,
                connected = True,
                competing = True,
                fail = '',
                message = '',
                prompts = [
                    ''
                    ]
            )
        else:
            return AuthStatus(
        )
        """

    def testAuthStatus(self):
        """Test AuthStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
