# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.allocation_inner_sector import AllocationInnerSector

class TestAllocationInnerSector(unittest.TestCase):
    """AllocationInnerSector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllocationInnerSector:
        """Test AllocationInnerSector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllocationInnerSector`
        """
        model = AllocationInnerSector()
        if include_optional:
            return AllocationInnerSector(
                long = openapi_client.models.allocation_inner_sector_long.allocation_inner_sector_long(
                    others = 1.337, 
                    utilities = 1.337, 
                    energy = 1.337, 
                    technology = 1.337, 
                    financial = 1.337, 
                    communications = 1.337, ),
                short = openapi_client.models.allocation_inner_sector_short.allocation_inner_sector_short(
                    industrial = 1.337, 
                    consumer = 1.337, 
                    diversified = 1.337, )
            )
        else:
            return AllocationInnerSector(
        )
        """

    def testAllocationInnerSector(self):
        """Test AllocationInnerSector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
