# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fyi_disclaimer_typecode_get200_response import FyiDisclaimerTypecodeGet200Response

class TestFyiDisclaimerTypecodeGet200Response(unittest.TestCase):
    """FyiDisclaimerTypecodeGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FyiDisclaimerTypecodeGet200Response:
        """Test FyiDisclaimerTypecodeGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FyiDisclaimerTypecodeGet200Response`
        """
        model = FyiDisclaimerTypecodeGet200Response()
        if include_optional:
            return FyiDisclaimerTypecodeGet200Response(
                dt = '',
                fc = ''
            )
        else:
            return FyiDisclaimerTypecodeGet200Response(
        )
        """

    def testFyiDisclaimerTypecodeGet200Response(self):
        """Test FyiDisclaimerTypecodeGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
