# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.portfolio_api import PortfolioApi


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortfolioApi()

    def tearDown(self) -> None:
        pass

    def test_portfolio_account_id_allocation_get(self) -> None:
        """Test case for portfolio_account_id_allocation_get

        Account Allocation
        """
        pass

    def test_portfolio_account_id_ledger_get(self) -> None:
        """Test case for portfolio_account_id_ledger_get

        Account Ledger
        """
        pass

    def test_portfolio_account_id_meta_get(self) -> None:
        """Test case for portfolio_account_id_meta_get

        Account Information
        """
        pass

    def test_portfolio_account_id_position_conid_get(self) -> None:
        """Test case for portfolio_account_id_position_conid_get

        Position by Conid
        """
        pass

    def test_portfolio_account_id_positions_invalidate_post(self) -> None:
        """Test case for portfolio_account_id_positions_invalidate_post

        Invalidates the backend cache of the Portfolio
        """
        pass

    def test_portfolio_account_id_positions_page_id_get(self) -> None:
        """Test case for portfolio_account_id_positions_page_id_get

        Portfolio Positions
        """
        pass

    def test_portfolio_account_id_summary_get(self) -> None:
        """Test case for portfolio_account_id_summary_get

        Account Summary
        """
        pass

    def test_portfolio_accounts_get(self) -> None:
        """Test case for portfolio_accounts_get

        Portfolio Accounts
        """
        pass

    def test_portfolio_allocation_post(self) -> None:
        """Test case for portfolio_allocation_post

        Account Alloction (All Accounts)
        """
        pass

    def test_portfolio_positions_conid_get(self) -> None:
        """Test case for portfolio_positions_conid_get

        Positions by Conid
        """
        pass

    def test_portfolio_subaccounts2_get(self) -> None:
        """Test case for portfolio_subaccounts2_get

        List of Sub-Accounts (Large Accounts)
        """
        pass

    def test_portfolio_subaccounts_get(self) -> None:
        """Test case for portfolio_subaccounts_get

        List of Sub-Accounts
        """
        pass


if __name__ == '__main__':
    unittest.main()
