# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.performance_tpps import PerformanceTpps

class TestPerformanceTpps(unittest.TestCase):
    """PerformanceTpps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformanceTpps:
        """Test PerformanceTpps
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformanceTpps`
        """
        model = PerformanceTpps()
        if include_optional:
            return PerformanceTpps(
                dates = [
                    ''
                    ],
                freq = '',
                data = [
                    openapi_client.models.performance_cps_data_inner.performance_cps_data_inner(
                        id = '', 
                        id_type = '', 
                        start = '', 
                        base_currency = '', 
                        returns = [
                            1.337
                            ], 
                        end = '', )
                    ]
            )
        else:
            return PerformanceTpps(
        )
        """

    def testPerformanceTpps(self):
        """Test PerformanceTpps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
