# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.iserver_reply_replyid_post200_response_inner import IserverReplyReplyidPost200ResponseInner

class TestIserverReplyReplyidPost200ResponseInner(unittest.TestCase):
    """IserverReplyReplyidPost200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IserverReplyReplyidPost200ResponseInner:
        """Test IserverReplyReplyidPost200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IserverReplyReplyidPost200ResponseInner`
        """
        model = IserverReplyReplyidPost200ResponseInner()
        if include_optional:
            return IserverReplyReplyidPost200ResponseInner(
                order_id = '',
                order_status = '',
                local_order_id = ''
            )
        else:
            return IserverReplyReplyidPost200ResponseInner(
        )
        """

    def testIserverReplyReplyidPost200ResponseInner(self):
        """Test IserverReplyReplyidPost200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
