# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.alert_request_conditions_inner import AlertRequestConditionsInner

class TestAlertRequestConditionsInner(unittest.TestCase):
    """AlertRequestConditionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertRequestConditionsInner:
        """Test AlertRequestConditionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertRequestConditionsInner`
        """
        model = AlertRequestConditionsInner()
        if include_optional:
            return AlertRequestConditionsInner(
                type = 56,
                conidex = '8314@SMART',
                operator = '>=',
                trigger_method = '0',
                value = '220',
                logic_bind = '',
                time_zone = ''
            )
        else:
            return AlertRequestConditionsInner(
        )
        """

    def testAlertRequestConditionsInner(self):
        """Test AlertRequestConditionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
