# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MarketData(BaseModel):
    """
    MarketData
    """ # noqa: E501
    var_31: Optional[StrictStr] = Field(default=None, description="Last Price - The last price at which the contract traded. May contain one of the following prefixes:   * C - Previous day's closing price.   * H - Trading has halted. ", alias="31")
    var_70: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="High - Current day high price", alias="70")
    var_71: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Low - Current day low price", alias="71")
    var_82: Optional[StrictStr] = Field(default=None, description="Change - The difference between the last price and the close on the previous trading day", alias="82")
    var_83: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Change % - The difference between the last price and the close on the previous trading day in percentage.", alias="83")
    var_84: Optional[StrictStr] = Field(default=None, description="Bid Price - The highest-priced bid on the contract.", alias="84")
    var_85: Optional[StrictStr] = Field(default=None, description="Ask Size - The number of contracts or shares offered at the ask price. For US stocks, the number displayed is divided by 100.", alias="85")
    var_86: Optional[StrictStr] = Field(default=None, description="Ask Price - The lowest-priced offer on the contract.", alias="86")
    var_87: Optional[StrictStr] = Field(default=None, description="Volume - Volume for the day, formatted with 'K' for thousands or 'M' for millions. For higher precision volume refer to field 7762.", alias="87")
    var_88: Optional[StrictStr] = Field(default=None, description="Bid Size - The number of contracts or shares bid for at the bid price. For US stocks, the number displayed is divided by 100.", alias="88")
    var_6509: Optional[StrictStr] = Field(default=None, description="Market Data Availability. The field may contain three chars. First char defines: R = RealTime, D = Delayed, Z = Frozen, Y = Frozen Delayed, N = Not Subscribed. Second char defines: P = Snapshot, p = Consolidated. Third char defines: B = Book   * RealTime - Data is relayed back in real time without delay, market data subscription(s) are required.   * Delayed - Data is relayed back 15-20 min delayed.   * Frozen - Last recorded data at market close, relayed back in real time.   * Frozen Delayed - Last recorded data at market close, relayed back delayed.   * Not Subscribed - User does not have the required market data subscription(s) to relay back either real time or delayed data.   * Snapshot - Snapshot request is available for contract.   * Consolidated - Market data is aggregated across multiple exchanges or venues.   * Book - Top of the book data is available for contract. ", alias="6509")
    var_7057: Optional[StrictStr] = Field(default=None, description="Ask Exch - Displays the exchange(s) offering the SMART price. A=AMEX, C=CBOE, I=ISE, X=PHLX, N=PSE, B=BOX, Q=NASDAQOM, Z=BATS, W=CBOE2, T=NASDAQBX, M=MIAX, H=GEMINI, E=EDGX, J=MERCURY", alias="7057")
    var_7058: Optional[StrictStr] = Field(default=None, description="Last Exch - Displays the exchange(s) offering the SMART price. A=AMEX, C=CBOE, I=ISE, X=PHLX, N=PSE, B=BOX, Q=NASDAQOM, Z=BATS, W=CBOE2, T=NASDAQBX, M=MIAX, H=GEMINI, E=EDGX, J=MERCURY", alias="7058")
    var_7059: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Last Size - The number of unites traded at the last price", alias="7059")
    var_7068: Optional[StrictStr] = Field(default=None, description="Bid Exch - Displays the exchange(s) offering the SMART price. A=AMEX, C=CBOE, I=ISE, X=PHLX, N=PSE, B=BOX, Q=NASDAQOM, Z=BATS, W=CBOE2, T=NASDAQBX, M=MIAX, H=GEMINI, E=EDGX, J=MERCURY", alias="7068")
    var_7195: Optional[StrictStr] = Field(default=None, description="IV Rank", alias="7195")
    var_7196: Optional[StrictStr] = Field(default=None, description="IV Rank", alias="7196")
    var_7197: Optional[StrictStr] = Field(default=None, description="IV Rank", alias="7197")
    var_7198: Optional[StrictStr] = Field(default=None, description="IV Percentile", alias="7198")
    var_7199: Optional[StrictStr] = Field(default=None, description="IV Percentile", alias="7199")
    var_7200: Optional[StrictStr] = Field(default=None, description="IV Percentile", alias="7200")
    var_7201: Optional[StrictStr] = Field(default=None, description="IV High Low", alias="7201")
    var_7202: Optional[StrictStr] = Field(default=None, description="IV High Low", alias="7202")
    var_7203: Optional[StrictStr] = Field(default=None, description="IV High Low", alias="7203")
    var_7204: Optional[StrictStr] = Field(default=None, description="IV High Low", alias="7204")
    var_7205: Optional[StrictStr] = Field(default=None, description="IV High Low", alias="7205")
    var_7206: Optional[StrictStr] = Field(default=None, description="IV High Low", alias="7206")
    var_7207: Optional[StrictStr] = Field(default=None, description="HV Rank", alias="7207")
    var_7208: Optional[StrictStr] = Field(default=None, description="HV Rank", alias="7208")
    var_7209: Optional[StrictStr] = Field(default=None, description="HV Rank", alias="7209")
    var_7210: Optional[StrictStr] = Field(default=None, description="HV Percentile", alias="7210")
    var_7211: Optional[StrictStr] = Field(default=None, description="HV Percentile", alias="7211")
    var_7212: Optional[StrictStr] = Field(default=None, description="HV Percentile", alias="7212")
    var_7245: Optional[StrictStr] = Field(default=None, description="HV High Low", alias="7245")
    var_7246: Optional[StrictStr] = Field(default=None, description="HV High Low", alias="7246")
    var_7247: Optional[StrictStr] = Field(default=None, description="HV High Low", alias="7247")
    var_7248: Optional[StrictStr] = Field(default=None, description="HV High Low", alias="7248")
    var_7249: Optional[StrictStr] = Field(default=None, description="HV High Low", alias="7249")
    var_7263: Optional[StrictStr] = Field(default=None, description="HV High Low", alias="7263")
    var_7264: Optional[StrictStr] = Field(default=None, description="ESG", alias="7264")
    var_7265: Optional[StrictStr] = Field(default=None, description="ESG", alias="7265")
    var_7266: Optional[StrictStr] = Field(default=None, description="ESG", alias="7266")
    var_7267: Optional[StrictStr] = Field(default=None, description="ESG", alias="7267")
    var_7268: Optional[StrictStr] = Field(default=None, description="ESG", alias="7268")
    var_7269: Optional[StrictStr] = Field(default=None, description="ESG", alias="7269")
    var_7271: Optional[StrictStr] = Field(default=None, description="ESG", alias="7271")
    var_7272: Optional[StrictStr] = Field(default=None, description="ESG", alias="7272")
    var_7273: Optional[StrictStr] = Field(default=None, description="ESG", alias="7273")
    var_7274: Optional[StrictStr] = Field(default=None, description="ESG", alias="7274")
    var_7275: Optional[StrictStr] = Field(default=None, description="ESG", alias="7275")
    var_7276: Optional[StrictStr] = Field(default=None, description="ESG", alias="7276")
    var_7277: Optional[StrictStr] = Field(default=None, description="ESG", alias="7277")
    var_7282: Optional[StrictStr] = Field(default=None, description="Average Volume - The average daily trading volume over 90 days.", alias="7282")
    var_7283: Optional[StrictStr] = Field(default=None, description="Option Implied Vol. % - A prediction of how volatile an underlying will be in the future. At the market volatility estimated for a maturity thirty calendar days forward of the current trading day, and based on option prices from two consecutive expiration months.      ", alias="7283")
    var_7284: Optional[StrictStr] = Field(default=None, description="Historic Volume (30d)", alias="7284")
    var_7286: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Dividend Amount - Displays the amount of the next dividend.", alias="7286")
    var_7287: Optional[StrictStr] = Field(default=None, description="Dividend Yield % - This value is the toal of the expected dividend payments over the next twelve months per share divided by the Current Price and is expressed as a percentage. For derivatives, this displays the total of the expected dividend payments over the expiry date. ", alias="7287")
    var_7288: Optional[StrictStr] = Field(default=None, description="Ex-date of the dividend", alias="7288")
    var_7289: Optional[StrictStr] = Field(default=None, description="Market Cap", alias="7289")
    var_7290: Optional[StrictStr] = Field(default=None, description="P/E", alias="7290")
    var_7293: Optional[StrictStr] = Field(default=None, description="52 Week High - The highest price for the past 52 weeks.", alias="7293")
    var_7294: Optional[StrictStr] = Field(default=None, description="52 Week Low - The lowest price for the past 52 weeks.", alias="7294")
    var_7295: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Open - Today's opening price.", alias="7295")
    var_7296: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Close - Today's closing price.", alias="7296")
    var_7331: Optional[StrictStr] = Field(default=None, description="Reuters Fundamentals", alias="7331")
    var_7370: Optional[StrictStr] = Field(default=None, description="ESG", alias="7370")
    var_7371: Optional[StrictStr] = Field(default=None, description="ESG", alias="7371")
    var_7372: Optional[StrictStr] = Field(default=None, description="ESG", alias="7372")
    var_7635: Optional[StrictStr] = Field(default=None, description="Mark - The mark price is, the ask price if ask is less than last price, the bid price if bid is more than the last price, otherwise it's equal to last price", alias="7635")
    var_7636: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="shortable invetory", alias="7636")
    var_7637: Optional[StrictStr] = Field(default=None, description="Fee rebate rate", alias="7637")
    var_7644: Optional[StrictStr] = Field(default=None, description="Shortable - Describes the level of difficulty with which the security can be sold short.", alias="7644")
    var_7674: Optional[StrictStr] = Field(default=None, description="EMA(200) - Exponential moving average (N=200).", alias="7674")
    var_7675: Optional[StrictStr] = Field(default=None, description="EMA(100) - Exponential moving average (N=100).", alias="7675")
    var_7676: Optional[StrictStr] = Field(default=None, description="EMA(50) - Exponential moving average (N=50).", alias="7676")
    var_7677: Optional[StrictStr] = Field(default=None, description="EMA(20) - Exponential moving average (N=20).", alias="7677")
    var_7681: Optional[StrictStr] = Field(default=None, description="Price/EMA(20) - Price to Exponential moving average (N=20) ratio -1, displayed in percents.", alias="7681")
    var_7698: Optional[StrictStr] = Field(default=None, description="Last Yield - Implied yield of the bond if it is purchased at the current last price. Last yield is calculated using the Last price on all possible call dates. It is assumed that prepayment occurs if the bond has call or put provisions and the issuer can offer a lower coupon rate based on current market rates. The yield to worst will be the lowest of the yield to maturity or yield to call (if the bond has prepayment provisions). Yield to worse may be the same as yield to maturity but never higher. ", alias="7698")
    var_7699: Optional[StrictStr] = Field(default=None, description="Bid Yield - Implied yield of the bond if it is purchased at the current bid price. Bid yield is calculated using the Ask on all possible call dates. It is assumed that prepayment occurs if the bond has call or put provisions and the issuer can offer a lower coupon rate based on current market rates. The yield to worst will be the lowest of the yield to maturity or yield to call (if the bond has prepayment provisions). Yield to worse may be the same as yield to maturity but never higher. ", alias="7699")
    var_7718: Optional[StrictStr] = Field(default=None, description="Beta - Beta is against standard index.", alias="7718")
    var_7720: Optional[StrictStr] = Field(default=None, description="Ask Yield - Implied yield of the bond if it is purchased at the current offer. Ask yield is calculated using the Bid on all possible call dates. It is assumed that prepayment occurs if the bond has call or put provisions and the issuer can offer a lower coupon rate based on current market rates. The yield to worst will be the lowest of the yield to maturity or yield to call (if the bond has prepayment provisions). Yield to worse may be the same as yield to maturity but never higher. ", alias="7720")
    var_7743: Optional[StrictStr] = Field(default=None, description="Reuters Fundamentals", alias="7743")
    var_7761: Optional[StrictStr] = Field(default=None, description="ESG", alias="7761")
    var_7992: Optional[StrictStr] = Field(default=None, description="26 Week High - The highest price for the past 26 weeks.", alias="7992")
    var_7993: Optional[StrictStr] = Field(default=None, description="26 Week Low - The lowest price for the past 26 weeks.", alias="7993")
    var_7994: Optional[StrictStr] = Field(default=None, description="13 Week High - The highest price for the past 13 weeks.", alias="7994")
    var_7995: Optional[StrictStr] = Field(default=None, description="13 Week Low - The lowest price for the past 13 weeks.", alias="7995")
    conid: Optional[StrictInt] = Field(default=None, description="IBKR Contract identifier")
    min_tick: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="minimum price increment", alias="minTick")
    bbo_exchange: Optional[StrictStr] = Field(default=None, description="Color for Best Bid/Offer Exchange in hex code", alias="BboExchange")
    has_delayed: Optional[StrictBool] = Field(default=None, description="If market data field values return delayed", alias="HasDelayed")
    size_min_tick: Optional[StrictInt] = Field(default=None, description="minimum size increment", alias="sizeMinTick")
    best_eligible: Optional[StrictInt] = Field(default=None, alias="BestEligible")
    best_bid_exch: Optional[StrictInt] = Field(default=None, alias="BestBidExch")
    best_ask_exch: Optional[StrictInt] = Field(default=None, alias="BestAskExch")
    pre_open_bid: Optional[StrictInt] = Field(default=None, alias="PreOpenBid")
    last_attribs: Optional[StrictInt] = Field(default=None, alias="LastAttribs")
    timestamp_base: Optional[StrictInt] = Field(default=None, description="Base time stamp for last update in format YYYYMMDD", alias="TimestampBase")
    timestamp_delta: Optional[StrictInt] = Field(default=None, alias="TimestampDelta")
    last_exch: Optional[StrictInt] = Field(default=None, alias="LastExch")
    close_attribs: Optional[StrictInt] = Field(default=None, alias="CloseAttribs")
    __properties: ClassVar[List[str]] = ["31", "70", "71", "82", "83", "84", "85", "86", "87", "88", "6509", "7057", "7058", "7059", "7068", "7195", "7196", "7197", "7198", "7199", "7200", "7201", "7202", "7203", "7204", "7205", "7206", "7207", "7208", "7209", "7210", "7211", "7212", "7245", "7246", "7247", "7248", "7249", "7263", "7264", "7265", "7266", "7267", "7268", "7269", "7271", "7272", "7273", "7274", "7275", "7276", "7277", "7282", "7283", "7284", "7286", "7287", "7288", "7289", "7290", "7293", "7294", "7295", "7296", "7331", "7370", "7371", "7372", "7635", "7636", "7637", "7644", "7674", "7675", "7676", "7677", "7681", "7698", "7699", "7718", "7720", "7743", "7761", "7992", "7993", "7994", "7995", "conid", "minTick", "BboExchange", "HasDelayed", "sizeMinTick", "BestEligible", "BestBidExch", "BestAskExch", "PreOpenBid", "LastAttribs", "TimestampBase", "TimestampDelta", "LastExch", "CloseAttribs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "31": obj.get("31"),
            "70": obj.get("70"),
            "71": obj.get("71"),
            "82": obj.get("82"),
            "83": obj.get("83"),
            "84": obj.get("84"),
            "85": obj.get("85"),
            "86": obj.get("86"),
            "87": obj.get("87"),
            "88": obj.get("88"),
            "6509": obj.get("6509"),
            "7057": obj.get("7057"),
            "7058": obj.get("7058"),
            "7059": obj.get("7059"),
            "7068": obj.get("7068"),
            "7195": obj.get("7195"),
            "7196": obj.get("7196"),
            "7197": obj.get("7197"),
            "7198": obj.get("7198"),
            "7199": obj.get("7199"),
            "7200": obj.get("7200"),
            "7201": obj.get("7201"),
            "7202": obj.get("7202"),
            "7203": obj.get("7203"),
            "7204": obj.get("7204"),
            "7205": obj.get("7205"),
            "7206": obj.get("7206"),
            "7207": obj.get("7207"),
            "7208": obj.get("7208"),
            "7209": obj.get("7209"),
            "7210": obj.get("7210"),
            "7211": obj.get("7211"),
            "7212": obj.get("7212"),
            "7245": obj.get("7245"),
            "7246": obj.get("7246"),
            "7247": obj.get("7247"),
            "7248": obj.get("7248"),
            "7249": obj.get("7249"),
            "7263": obj.get("7263"),
            "7264": obj.get("7264"),
            "7265": obj.get("7265"),
            "7266": obj.get("7266"),
            "7267": obj.get("7267"),
            "7268": obj.get("7268"),
            "7269": obj.get("7269"),
            "7271": obj.get("7271"),
            "7272": obj.get("7272"),
            "7273": obj.get("7273"),
            "7274": obj.get("7274"),
            "7275": obj.get("7275"),
            "7276": obj.get("7276"),
            "7277": obj.get("7277"),
            "7282": obj.get("7282"),
            "7283": obj.get("7283"),
            "7284": obj.get("7284"),
            "7286": obj.get("7286"),
            "7287": obj.get("7287"),
            "7288": obj.get("7288"),
            "7289": obj.get("7289"),
            "7290": obj.get("7290"),
            "7293": obj.get("7293"),
            "7294": obj.get("7294"),
            "7295": obj.get("7295"),
            "7296": obj.get("7296"),
            "7331": obj.get("7331"),
            "7370": obj.get("7370"),
            "7371": obj.get("7371"),
            "7372": obj.get("7372"),
            "7635": obj.get("7635"),
            "7636": obj.get("7636"),
            "7637": obj.get("7637"),
            "7644": obj.get("7644"),
            "7674": obj.get("7674"),
            "7675": obj.get("7675"),
            "7676": obj.get("7676"),
            "7677": obj.get("7677"),
            "7681": obj.get("7681"),
            "7698": obj.get("7698"),
            "7699": obj.get("7699"),
            "7718": obj.get("7718"),
            "7720": obj.get("7720"),
            "7743": obj.get("7743"),
            "7761": obj.get("7761"),
            "7992": obj.get("7992"),
            "7993": obj.get("7993"),
            "7994": obj.get("7994"),
            "7995": obj.get("7995"),
            "conid": obj.get("conid"),
            "minTick": obj.get("minTick"),
            "BboExchange": obj.get("BboExchange"),
            "HasDelayed": obj.get("HasDelayed"),
            "sizeMinTick": obj.get("sizeMinTick"),
            "BestEligible": obj.get("BestEligible"),
            "BestBidExch": obj.get("BestBidExch"),
            "BestAskExch": obj.get("BestAskExch"),
            "PreOpenBid": obj.get("PreOpenBid"),
            "LastAttribs": obj.get("LastAttribs"),
            "TimestampBase": obj.get("TimestampBase"),
            "TimestampDelta": obj.get("TimestampDelta"),
            "LastExch": obj.get("LastExch"),
            "CloseAttribs": obj.get("CloseAttribs")
        })
        return _obj


