# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class OrderRequest(BaseModel):
    """
    OrderRequest
    """ # noqa: E501
    acct_id: Optional[StrictStr] = Field(default=None, description="acctId is optional. It should be one of the accounts returned by /iserver/accounts. If not passed, the first one in the list is selected. ", alias="acctId")
    conid: Optional[StrictInt] = Field(default=None, description="conid is the identifier of the security you want to trade, you can find the conid with /iserver/secdef/search. ")
    conidex: Optional[StrictStr] = Field(default=None, description="Conid and Exchange - Can be used instead of conid when specifying the contract identifier of a security. ")
    sec_type: Optional[StrictStr] = Field(default=None, description="The contract-identifier (conid) and security type (type) specified as a concatenated value, conid:type", alias="secType")
    c_oid: Optional[StrictStr] = Field(default=None, description="Customer Order ID. An arbitrary string that can be used to identify the order, e.g \"my-fb-order\". The value must be unique for a 24h span. Please do not set this value for child orders when placing a bracket order. ", alias="cOID")
    parent_id: Optional[StrictStr] = Field(default=None, description="Only specify for child orders when placing bracket orders. The parentId for the child order(s) must be equal to the cOId (customer order id) of the parent. ", alias="parentId")
    order_type: Optional[StrictStr] = Field(default=None, description="The order-type determines what type of order you want to send.   * LMT - A limit order is an order to buy or sell at the specified price or better.   * MKT - A market order is an order to buy or sell at the markets current NBBO.   * STP - A stop order becomes a market order once the specified stop price is attained or penetrated.   * STOP_LIMIT - A stop limit order becomes a limit order once the specified stop price is attained or penetrated.   * MIDPRICE - A MidPrice order attempts to fill at the current midpoint of the NBBO or better.   * TRAIL - A sell trailing stop order sets the stop price at a fixed amount below the market price with an attached \"trailing\" amount. See more details here: https://ndcdyn.interactivebrokers.com/en/index.php?f=605   * TRAILLMT - A trailing stop limit order is designed to allow an investor to specify a limit on the maximum possible loss, without setting a limit on the maximum possible gain.     See more details here: https://ndcdyn.interactivebrokers.com/en/index.php?f=606 ", alias="orderType")
    listing_exchange: Optional[StrictStr] = Field(default=None, description="listingExchange is optional. By default we use \"SMART\" routing. Possible values are available via the endpoint: /iserver/contract/{conid}/info, see **valid_exchange** e.g: SMART,AMEX,NYSE,CBOE,ISE,CHX,ARCA,ISLAND,DRCTEDGE,BEX,BATS,EDGEA,CSFBALGO,JE FFALGO,BYX,IEX,FOXRIVER,TPLUS1,NYSENAT,PSX ", alias="listingExchange")
    is_single_group: Optional[StrictBool] = Field(default=None, description="set to true if you want to place a single group orders(OCA) ", alias="isSingleGroup")
    outside_rth: Optional[StrictBool] = Field(default=None, description="set to true if the order can be executed outside regular trading hours. ", alias="outsideRTH")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="optional if order is LMT, or STOP_LIMIT, this is the limit price. For STP|TRAIL this is the stop price. For MIDPRICE this is the option price cap. ")
    aux_price: Optional[Dict[str, Any]] = Field(default=None, description="optional if order is STOP_LIMIT|TRAILLMT, this is the stop price. You must specify both price and auxPrice for STOP_LIMIT|TRAILLMT orders. ", alias="auxPrice")
    side: Optional[StrictStr] = Field(default=None, description="SELL or BUY")
    ticker: Optional[StrictStr] = Field(default=None, description="This is the  underlying symbol for the contract. ")
    tif: Optional[StrictStr] = Field(default=None, description="The Time-In-Force determines how long the order remains active on the market.   * GTC - use Good-Till-Cancel for orders to remain active until it executes or cancelled.   * OPG - use Open-Price-Guarantee for Limit-On-Open (LOO) or Market-On-Open (MOO) orders.   * DAY - if not executed a Day order will automatically cancel at the end of the markets regular trading hours.   * IOC - any portion of an Immediate-or-Cancel order that is not filled as soon as it becomes available in the market is cancelled. ")
    trailing_amt: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="optional if order is TRAIL, or TRAILLMT. When trailingType is amt, this is the trailing amount, when trailingType is %, it means percentage. You must specify both trailingType and trailingAmt for TRAIL and TRAILLMT order ", alias="trailingAmt")
    trailing_type: Optional[StrictStr] = Field(default=None, description="This is the trailing type for trailing amount. We only support two types here: amt or %. You must specify both trailingType and trailingAmt for TRAIL and TRAILLMT order ", alias="trailingType")
    referrer: Optional[StrictStr] = Field(default=None, description="Custom order reference ")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Usually integer, for some special cases such as fractional orders can specify as a float, e.g. quantity = 0.001. In some special cases quantity is not specified, such as when using 'cashQty' or 'fxQty'. ")
    cash_qty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Cash Quantity - used to specify the monetary value of an order instead of the number of shares. When using 'cashQty' don't specify 'quantity' Orders that express size using a monetary value, e.g. cash quantity can result in fractional shares and are provided on a non-guaranteed basis. The system simulates the order by canceling it once the specified amount is spent (for buy orders) or collected (for sell orders). In addition to the monetary value, the order uses a maximum size that is calculated using the Cash Quantity Estimated Factor, which can be modified in Order Presets.   ", alias="cashQty")
    fx_qty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="double number, this is the cash quantity field which can only be used for Currency Conversion Orders. When using 'fxQty' don't specify 'quantity'. ", alias="fxQty")
    use_adaptive: Optional[StrictBool] = Field(default=None, description="If true, the system will use the Price Management Algo to submit the order. https://www.interactivebrokers.com/en/index.php?f=43423 ", alias="useAdaptive")
    is_ccy_conv: Optional[StrictBool] = Field(default=None, description="set to true if the order is a FX conversion order ", alias="isCcyConv")
    allocation_method: Optional[StrictStr] = Field(default=None, description="Set the allocation method when placing an order using an FA account for a group Possible allocation methods are \"NetLiquidity\", \"AvailableEquity\", \"EqualQuantity\" and \"PctChange\". ", alias="allocationMethod")
    strategy: Optional[StrictStr] = Field(default=None, description="Specify which IB Algo algorithm to use for this order. ")
    strategy_parameters: Optional[Dict[str, Any]] = Field(default=None, description="The IB Algo parameters for the specified algorithm. ", alias="strategyParameters")
    __properties: ClassVar[List[str]] = ["acctId", "conid", "conidex", "secType", "cOID", "parentId", "orderType", "listingExchange", "isSingleGroup", "outsideRTH", "price", "auxPrice", "side", "ticker", "tif", "trailingAmt", "trailingType", "referrer", "quantity", "cashQty", "fxQty", "useAdaptive", "isCcyConv", "allocationMethod", "strategy", "strategyParameters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acctId": obj.get("acctId"),
            "conid": obj.get("conid"),
            "conidex": obj.get("conidex"),
            "secType": obj.get("secType"),
            "cOID": obj.get("cOID"),
            "parentId": obj.get("parentId"),
            "orderType": obj.get("orderType"),
            "listingExchange": obj.get("listingExchange"),
            "isSingleGroup": obj.get("isSingleGroup"),
            "outsideRTH": obj.get("outsideRTH"),
            "price": obj.get("price"),
            "auxPrice": obj.get("auxPrice"),
            "side": obj.get("side"),
            "ticker": obj.get("ticker"),
            "tif": obj.get("tif"),
            "trailingAmt": obj.get("trailingAmt"),
            "trailingType": obj.get("trailingType"),
            "referrer": obj.get("referrer"),
            "quantity": obj.get("quantity"),
            "cashQty": obj.get("cashQty"),
            "fxQty": obj.get("fxQty"),
            "useAdaptive": obj.get("useAdaptive"),
            "isCcyConv": obj.get("isCcyConv"),
            "allocationMethod": obj.get("allocationMethod"),
            "strategy": obj.get("strategy"),
            "strategyParameters": obj.get("strategyParameters")
        })
        return _obj


