# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ContractRules(BaseModel):
    """
    ContractRules
    """ # noqa: E501
    order_types: Optional[List[StrictStr]] = Field(default=None, alias="orderTypes")
    order_types_outside: Optional[List[StrictStr]] = Field(default=None, alias="orderTypesOutside")
    default_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="default quantity you can use to place an order", alias="defaultSize")
    size_increment: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="sizeIncrement")
    tif_types: Optional[List[StrictStr]] = Field(default=None, alias="tifTypes")
    limit_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="default limit price you can use to prefill your order", alias="limitPrice")
    stopprice: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="default stop price you can use to prefill your order")
    preview: Optional[StrictBool] = Field(default=None, description="if you can preview the order or not with the whatif endpoint")
    display_size: Optional[StrictStr] = Field(default=None, alias="displaySize")
    increment: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["orderTypes", "orderTypesOutside", "defaultSize", "sizeIncrement", "tifTypes", "limitPrice", "stopprice", "preview", "displaySize", "increment"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractRules from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractRules from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orderTypes": obj.get("orderTypes"),
            "orderTypesOutside": obj.get("orderTypesOutside"),
            "defaultSize": obj.get("defaultSize"),
            "sizeIncrement": obj.get("sizeIncrement"),
            "tifTypes": obj.get("tifTypes"),
            "limitPrice": obj.get("limitPrice"),
            "stopprice": obj.get("stopprice"),
            "preview": obj.get("preview"),
            "displaySize": obj.get("displaySize"),
            "increment": obj.get("increment")
        })
        return _obj


