# coding: utf-8

"""
    Client Portal Web API

    Client Poral Web API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class NotificationsInner(BaseModel):
    """
    notification
    """ # noqa: E501
    d: Optional[StrictStr] = Field(default=None, description="notification date", alias="D")
    id: Optional[StrictStr] = Field(default=None, description="unique way to reference this notification", alias="ID")
    fc: Optional[StrictStr] = Field(default=None, description="FYI code, we can use it to find whether the disclaimer is accepted or not in settings", alias="FC")
    md: Optional[StrictStr] = Field(default=None, description="content of notification", alias="MD")
    ms: Optional[StrictStr] = Field(default=None, description="title of notification", alias="MS")
    r: Optional[StrictStr] = Field(default=None, description="0-unread, 1-read", alias="R")
    __properties: ClassVar[List[str]] = ["D", "ID", "FC", "MD", "MS", "R"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "D": obj.get("D"),
            "ID": obj.get("ID"),
            "FC": obj.get("FC"),
            "MD": obj.get("MD"),
            "MS": obj.get("MS"),
            "R": obj.get("R")
        })
        return _obj


